"""Generated by scripts/build_site_dossier.py from results/. Do not edit.

tests/test_site_dossier.py fails if this drifts from results/.
"""

SITE_116 = {'site': '116 縣道 樹林中正路,雙白實線起點(「往板橋/往樹林」標字)往橋頭',
 'measured_from_this_photograph': False,
 'items': [{'what': '雙白實線起點到橋頭',
            'value_m': 85.0,
            'pm_m': 5.0,
            'source': 'results/solid_line_extent.json#/extents/solid_plus_chevron_to_bridge_head_m'},
           {'what': '其中實線段(不准變換車道)',
            'value_m': 35.5,
            'pm_m': 5.0,
            'source': 'results/solid_line_extent.json#/extents/solid_line_before_chevron_m'},
           {'what': '格柵溝蓋位置',
            'value_m': [8, 16, 28, 44, 58, 74, 82],
            'pm_m': 5,
            'count': 7,
            'source': 'results/solid_line_extent.json#/drain_covers/grates_along_m'},
           {'what': '紅線外移(新紅線內緣到舊紅線中心)',
            'value_m': {'F30': 0.68, 'F31': 0.669, 'F32': 0.635},
            'source': 'results/redline_gap_F30.json, _F31.json, _F32.json#/summary/median_m'},
           {'what': '槽化線段扣反應 2.5 s 後可併道的時間,50 km/h',
            'value_s': 1.1,
            'source': 'results/merge_window.json#/rows/kmh=50'},
           {'what': '同上,30 km/h',
            'value_s': 3.4,
            'source': 'results/merge_window.json#/rows/kmh=30'},
           {'what': '槽化線漸變率(表 4.2.7:50 km/h 要 16:1)',
            'value_ratio': {'min': 9.2, 'max': 11.9},
            'frames': ['F17', 'F40'],
            'source': 'results/taper_phone.json#/summary',
            'stability': '2026-09-23:原檔以 JPEG 品質 97 重新編碼一次,F17 即拒答、F40 由 11.9 變 '
                         '23.2。此數字對編碼不穩,待重新檢驗(isolation/field-2026-09-23/NOTES.md)'}]}
