#!/usr/bin/env python3
"""Write src/marking/site_116.py: the 116 縣道 numbers the endpoint attaches.

The endpoint image copies src/ only (aws/Dockerfile), so the site's
published figures are frozen into a module here. Every value is read
from results/ and carries the file and key it came from;
tests/test_site_dossier.py re-reads results/ and fails if they drift.

None of this is measured from the caller's photograph. The endpoint
attaches it to every response, by the owner's decision (2026-09-23), under
a key that says so.

    /opt/anaconda3/bin/python3 -B scripts/build_site_dossier.py
"""
import json
import pprint
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load(name):
    return json.loads((ROOT / "results" / name).read_text())


def build():
    ext = load("solid_line_extent.json")
    mw = load("merge_window.json")
    tp = load("taper_phone.json")
    gaps = {f: load(f"redline_gap_{f}.json")["summary"] for f in ("F30", "F31", "F32")}
    rows = {r["kmh"]: r for r in mw["rows"]}
    e = ext["extents"]
    return {
        "site": "116 縣道 樹林中正路,雙白實線起點(「往板橋/往樹林」標字)往橋頭",
        "measured_from_this_photograph": False,
        "items": [
            {"what": "雙白實線起點到橋頭", "value_m": e["solid_plus_chevron_to_bridge_head_m"],
             "pm_m": e["uncertainty_m"], "source": "results/solid_line_extent.json#/extents/solid_plus_chevron_to_bridge_head_m"},
            {"what": "其中實線段(不准變換車道)", "value_m": e["solid_line_before_chevron_m"],
             "pm_m": e["uncertainty_m"], "source": "results/solid_line_extent.json#/extents/solid_line_before_chevron_m"},
            {"what": "格柵溝蓋位置", "value_m": ext["drain_covers"]["grates_along_m"],
             "pm_m": ext["drain_covers"]["uncertainty_m"], "count": ext["drain_covers"]["count_0_to_85_m"],
             "source": "results/solid_line_extent.json#/drain_covers/grates_along_m"},
            {"what": "紅線外移(新紅線內緣到舊紅線中心)",
             "value_m": {f: g["median_m"] for f, g in gaps.items()},
             "source": "results/redline_gap_F30.json, _F31.json, _F32.json#/summary/median_m"},
            {"what": "槽化線段扣反應 2.5 s 後可併道的時間,50 km/h",
             "value_s": rows[50]["window_after_reaction_s"], "source": "results/merge_window.json#/rows/kmh=50"},
            {"what": "同上,30 km/h", "value_s": rows[30]["window_after_reaction_s"],
             "source": "results/merge_window.json#/rows/kmh=30"},
            {"what": "槽化線漸變率(表 4.2.7:50 km/h 要 16:1)",
             "value_ratio": {"min": tp["summary"]["ratio_min"], "max": tp["summary"]["ratio_max"]},
             "frames": tp["summary"]["frames_ok"], "source": "results/taper_phone.json#/summary",
             "stability": "2026-09-23:原檔以 JPEG 品質 97 重新編碼一次,F17 即拒答、F40 由 11.9 變 23.2。"
                          "此數字對編碼不穩,待重新檢驗(isolation/field-2026-09-23/NOTES.md)"},
        ],
    }


def main():
    d = build()
    text = ('"""Generated by scripts/build_site_dossier.py from results/. Do not edit.\n\n'
            'tests/test_site_dossier.py fails if this drifts from results/.\n"""\n\n'
            "SITE_116 = " + pprint.pformat(d, width=100, sort_dicts=False) + "\n")
    (ROOT / "src" / "marking" / "site_116.py").write_text(text)
    print("寫入 src/marking/site_116.py")


if __name__ == "__main__":
    main()
